### ISSUE TITLE
App crashed with out of bonds exception

### ISSUE THREAD

**Issue by Quik2007** [kaajjo/LibreSudoku#123]
Not quite sure what exactly I did, but the app crashed with the following back trace:

```
java.lang.IndexOutOfBoundsException: Index 124 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 124 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at okhttp3.internal.http.StatusLine.addState(Unknown Source:6)
	at com.kaajjo.libresudoku.ui.game.GameViewModel.processInput(Unknown Source:195)
	at com.kaajjo.libresudoku.ui.game.GameScreenKt$GameScreen$3$$ExternalSyntheticLambda0.invoke(Unknown Source:61)
	at com.ramcosta.composedestinations.DestinationsNavHostKt$$ExternalSyntheticLambda1.invoke(Unknown Source:101)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(Unknown Source:328)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.JobKt.resume(Unknown Source:80)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(Unknown Source:104)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:32)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:16)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(Unknown Source:50)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:30)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:156)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:135)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:135)
	at coil.ImageLoader$Builder.dispatchChanges(Unknown Source:35)
	at androidx.compose.material.ripple.StateLayer.process-BIzXfog(Unknown Source:140)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(Unknown Source:80)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(Unknown Source:374)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(Unknown Source:75)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2817)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2817)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2817)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2817)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2817)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2817)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:467)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1981)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4547)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:425)
	at android.view.View.dispatchPointerEvent(View.java:16743)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8031)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7791)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7180)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7237)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7203)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7369)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7211)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7426)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7184)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7237)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7203)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7211)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7184)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10319)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10270)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10238)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10461)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:358)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@fb48eb4, androidx.compose.runtime.BroadcastFrameClock@693cadd, DeferredCoroutine{Cancelling}@8aae652, AndroidUiDispatcher@85d3d23]

```

**Comment by metalwanderer** [comment]
I'm also getting this, although it's been working reliably for months. 
Seems to happen every time without fail, as soon as I try to enter a pencilmark.  Also tried restarting phone, no change. 

Stacktrace:
`java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at okhttp3.internal.http.StatusLine.addState(Unknown Source:6)
	at com.kaajjo.libresudoku.ui.game.GameViewModel.processInput(Unknown Source:195)
	at com.kaajjo.libresudoku.ui.game.GameScreenKt$GameScreen$3$$ExternalSyntheticLambda0.invoke(Unknown Source:61)
	at com.ramcosta.composedestinations.DestinationsNavHostKt$$ExternalSyntheticLambda1.invoke(Unknown Source:101)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(Unknown Source:328)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.JobKt.resume(Unknown Source:80)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(Unknown Source:104)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:32)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:16)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(Unknown Source:50)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:30)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:156)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:135)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:135)
	at coil.ImageLoader$Builder.dispatchChanges(Unknown Source:35)
	at androidx.compose.material.ripple.StateLayer.process-BIzXfog(Unknown Source:140)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(Unknown Source:80)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(Unknown Source:374)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(Unknown Source:75)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1910)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4377)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15931)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7045)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6841)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6255)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6312)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6278)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6443)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6286)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6500)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6259)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6312)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6278)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6286)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6259)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9246)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9197)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9161)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9372)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:268)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@fd7bdc8, androidx.compose.runtime.BroadcastFrameClock@b5eee61, DeferredCoroutine{Cancelling}@4133d86, AndroidUiDispatcher@4943647]
`
