### ISSUE TITLE
Index out of bound exception when trying to enter value in 9x9 

### ISSUE THREAD

**Issue by vigneshm01** [kaajjo/LibreSudoku#124]
java.lang.IndexOutOfBoundsException: Index 102 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 102 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at okhttp3.internal.http.StatusLine.addState(Unknown Source:6)
	at com.kaajjo.libresudoku.ui.game.GameViewModel.processInput(Unknown Source:195)
	at com.kaajjo.libresudoku.ui.game.GameScreenKt$GameScreen$3$$ExternalSyntheticLambda0.invoke(Unknown Source:61)
	at com.ramcosta.composedestinations.DestinationsNavHostKt$$ExternalSyntheticLambda1.invoke(Unknown Source:101)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(Unknown Source:328)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.JobKt.resume(Unknown Source:80)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(Unknown Source:104)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:32)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:16)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(Unknown Source:50)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:30)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:156)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:135)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:135)
	at coil.ImageLoader$Builder.dispatchChanges(Unknown Source:35)
	at androidx.compose.material.ripple.StateLayer.process-BIzXfog(Unknown Source:140)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(Unknown Source:80)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(Unknown Source:374)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(Unknown Source:75)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1980)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4533)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
	at android.view.View.dispatchPointerEvent(View.java:16730)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8005)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7771)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7160)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7183)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7349)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7191)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7406)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7164)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7183)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7191)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7164)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10296)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10247)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10211)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10442)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:351)
	at android.os.Looper.loopOnce(Looper.java:204)
	at android.os.Looper.loop(Looper.java:356)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:598)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:896)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@c97bef4, androidx.compose.runtime.BroadcastFrameClock@d82d61d, DeferredCoroutine{Cancelling}@5603092, AndroidUiDispatcher@bad5a63]

**Comment by vigneshm01** [comment]
duplicated
