### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by Fjara-h** [kaajjo/LibreSudoku#126]
I has just recently restarted a hard. Prior to this I was modifying the appearence settings a lot and prior to restarting I had enabled advanced hints. Let me know if any other information is helpful for debugging purposes.

Version 2.0.0 (20)
SM-G781U1/DS
Android 13

`java.lang.IndexOutOfBoundsException: Index 219 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 219 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at okhttp3.internal.http.StatusLine.addState(Unknown Source:6)
	at com.kaajjo.libresudoku.ui.game.GameViewModel.processInput(Unknown Source:195)
	at com.kaajjo.libresudoku.ui.game.GameScreenKt$GameScreen$3$$ExternalSyntheticLambda0.invoke(Unknown Source:61)
	at com.ramcosta.composedestinations.DestinationsNavHostKt$$ExternalSyntheticLambda1.invoke(Unknown Source:101)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(Unknown Source:328)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.JobKt.resume(Unknown Source:80)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(Unknown Source:104)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:32)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:16)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(Unknown Source:50)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:30)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:156)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:135)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:135)
	at coil.ImageLoader$Builder.dispatchChanges(Unknown Source:35)
	at androidx.compose.material.ripple.StateLayer.process-BIzXfog(Unknown Source:140)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(Unknown Source:80)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(Unknown Source:374)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(Unknown Source:75)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1116)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1971)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4388)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:1074)
	at android.view.View.dispatchPointerEvent(View.java:15803)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8153)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7877)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7213)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7434)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7491)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10788)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10676)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10632)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10926)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:285)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@f4ef5b9, androidx.compose.runtime.BroadcastFrameClock@9932dfe, DeferredCoroutine{Cancelling}@c22295f, AndroidUiDispatcher@1a0bfac]
`

**Comment by kaajjo** [comment]
Yep, seems to be related to #123
